import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { DemoPlan } from "@autodemo/video/schema";
import { readPlan } from "./compose";
import { log } from "./log";
import { CHANGELOG_FILE, OUT_DIR, OUT_MP4, PR_COMMENT_FILE, REPO_ROOT } from "./paths";

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function relMp4(): string {
  return path.relative(REPO_ROOT, OUT_MP4);
}

function changelogEntry(plan: DemoPlan): string {
  const lines = plan.scenes.map((s) => `- ${s.title || s.id}`);
  return [
    `## ${plan.brand.releaseTag} — ${today()}`,
    "",
    ...lines,
    "",
    `🎬 Demo video: \`${relMp4()}\``,
    "",
  ].join("\n");
}

function prComment(plan: DemoPlan): string {
  const list = plan.scenes.map((s) => `- **${s.title || s.id}**`).join("\n");
  return [
    `### AutoDemo — UI change preview`,
    "",
    `Generated automatically from this change. The clip shows the UI change in a screen-recording style, reproduced from the code.`,
    "",
    `**${plan.brand.productName} ${plan.brand.releaseTag}**${plan.brand.prNumber ? ` · PR #${plan.brand.prNumber}` : ""}`,
    "",
    list,
    "",
    `Video: \`${relMp4()}\` — 1920x1080 · 30fps · no audio.`,
    "",
    `<sub>Generated by AutoDemo from the PR diff.</sub>`,
  ].join("\n");
}

function prependChangelog(entry: string): void {
  let prev = "";
  if (fs.existsSync(CHANGELOG_FILE)) prev = fs.readFileSync(CHANGELOG_FILE, "utf8");
  const header = prev.startsWith("# Changelog") ? "" : "# Changelog\n\n";
  const body = prev.replace(/^# Changelog\n\n/, "");
  fs.writeFileSync(CHANGELOG_FILE, `${header}${entry}\n${body}`, "utf8");
}

function tryPostPrComment(prNumber: number, body: string): void {
  try {
    execFileSync("gh", ["pr", "comment", String(prNumber), "--body-file", PR_COMMENT_FILE], {
      cwd: REPO_ROOT,
      stdio: "inherit",
    });
    log.ok(`Posted comment to PR #${prNumber}.`);
  } catch (err) {
    log.warn(`Could not post via gh: ${(err as Error).message}`);
    log.info(`Post manually: gh pr comment ${prNumber} --body-file ${PR_COMMENT_FILE}`);
  }
}

export function publish(opts: { post?: boolean } = {}): void {
  const plan = readPlan();
  fs.mkdirSync(OUT_DIR, { recursive: true });

  if (!fs.existsSync(OUT_MP4)) {
    log.warn(`No video at ${OUT_MP4} yet — run \`autodemo render\` first.`);
  }

  prependChangelog(changelogEntry(plan));
  const comment = prComment(plan);
  fs.writeFileSync(PR_COMMENT_FILE, comment, "utf8");

  log.ok(`Changelog updated → ${path.relative(REPO_ROOT, CHANGELOG_FILE)}`);
  log.ok(`PR comment ready → ${path.relative(REPO_ROOT, PR_COMMENT_FILE)}`);

  if (opts.post && plan.brand.prNumber > 0) {
    tryPostPrComment(plan.brand.prNumber, comment);
  } else {
    log.info(
      `To post: gh pr comment ${plan.brand.prNumber || "<PR>"} --body-file ${path.relative(REPO_ROOT, PR_COMMENT_FILE)}`,
    );
  }
}
